// Code generated by protoc-gen-go from "urlfetch_service.proto"
// DO NOT EDIT!

package appengine

import proto "goprotobuf.googlecode.com/hg/proto"
import "math"
import "os"

// Reference proto, math & os imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf
var _ os.Error

type URLFetchServiceError_ErrorCode int32

const (
	URLFetchServiceError_OK                    URLFetchServiceError_ErrorCode = 0
	URLFetchServiceError_INVALID_URL           URLFetchServiceError_ErrorCode = 1
	URLFetchServiceError_FETCH_ERROR           URLFetchServiceError_ErrorCode = 2
	URLFetchServiceError_UNSPECIFIED_ERROR     URLFetchServiceError_ErrorCode = 3
	URLFetchServiceError_RESPONSE_TOO_LARGE    URLFetchServiceError_ErrorCode = 4
	URLFetchServiceError_DEADLINE_EXCEEDED     URLFetchServiceError_ErrorCode = 5
	URLFetchServiceError_SSL_CERTIFICATE_ERROR URLFetchServiceError_ErrorCode = 6
)

var URLFetchServiceError_ErrorCode_name = map[int32]string{
	0: "OK",
	1: "INVALID_URL",
	2: "FETCH_ERROR",
	3: "UNSPECIFIED_ERROR",
	4: "RESPONSE_TOO_LARGE",
	5: "DEADLINE_EXCEEDED",
	6: "SSL_CERTIFICATE_ERROR",
}
var URLFetchServiceError_ErrorCode_value = map[string]int32{
	"OK":                    0,
	"INVALID_URL":           1,
	"FETCH_ERROR":           2,
	"UNSPECIFIED_ERROR":     3,
	"RESPONSE_TOO_LARGE":    4,
	"DEADLINE_EXCEEDED":     5,
	"SSL_CERTIFICATE_ERROR": 6,
}

func NewURLFetchServiceError_ErrorCode(x URLFetchServiceError_ErrorCode) *URLFetchServiceError_ErrorCode {
	e := URLFetchServiceError_ErrorCode(x)
	return &e
}
func (x URLFetchServiceError_ErrorCode) String() string {
	return proto.EnumName(URLFetchServiceError_ErrorCode_name, int32(x))
}

type URLFetchRequest_RequestMethod int32

const (
	URLFetchRequest_GET    URLFetchRequest_RequestMethod = 1
	URLFetchRequest_POST   URLFetchRequest_RequestMethod = 2
	URLFetchRequest_HEAD   URLFetchRequest_RequestMethod = 3
	URLFetchRequest_PUT    URLFetchRequest_RequestMethod = 4
	URLFetchRequest_DELETE URLFetchRequest_RequestMethod = 5
)

var URLFetchRequest_RequestMethod_name = map[int32]string{
	1: "GET",
	2: "POST",
	3: "HEAD",
	4: "PUT",
	5: "DELETE",
}
var URLFetchRequest_RequestMethod_value = map[string]int32{
	"GET":    1,
	"POST":   2,
	"HEAD":   3,
	"PUT":    4,
	"DELETE": 5,
}

func NewURLFetchRequest_RequestMethod(x URLFetchRequest_RequestMethod) *URLFetchRequest_RequestMethod {
	e := URLFetchRequest_RequestMethod(x)
	return &e
}
func (x URLFetchRequest_RequestMethod) String() string {
	return proto.EnumName(URLFetchRequest_RequestMethod_name, int32(x))
}

type URLFetchServiceError struct {
	XXX_unrecognized []byte `json:",omitempty"`
}

func (this *URLFetchServiceError) Reset()         { *this = URLFetchServiceError{} }
func (this *URLFetchServiceError) String() string { return proto.CompactTextString(this) }

type URLFetchRequest struct {
	Method                        *URLFetchRequest_RequestMethod `protobuf:"varint,1,req,enum=appengine.URLFetchRequest_RequestMethod" json:"Method,omitempty"`
	Url                           *string                        `protobuf:"bytes,2,req" json:"Url,omitempty"`
	Header                        []*URLFetchRequest_Header      `protobuf:"group,3,rep" json:"header,omitempty"`
	Payload                       []byte                         `protobuf:"bytes,6,opt" json:"Payload,omitempty"`
	FollowRedirects               *bool                          `protobuf:"varint,7,opt,def=1" json:"FollowRedirects,omitempty"`
	Deadline                      *float64                       `protobuf:"fixed64,8,opt" json:"Deadline,omitempty"`
	MustValidateServerCertificate *bool                          `protobuf:"varint,9,opt,def=1" json:"MustValidateServerCertificate,omitempty"`
	XXX_unrecognized              []byte                         `json:",omitempty"`
}

func (this *URLFetchRequest) Reset()         { *this = URLFetchRequest{} }
func (this *URLFetchRequest) String() string { return proto.CompactTextString(this) }

const Default_URLFetchRequest_FollowRedirects bool = true
const Default_URLFetchRequest_MustValidateServerCertificate bool = true

type URLFetchRequest_Header struct {
	Key              *string `protobuf:"bytes,4,req" json:"Key,omitempty"`
	Value            *string `protobuf:"bytes,5,req" json:"Value,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *URLFetchRequest_Header) Reset()         { *this = URLFetchRequest_Header{} }
func (this *URLFetchRequest_Header) String() string { return proto.CompactTextString(this) }

type URLFetchResponse struct {
	Content               []byte                     `protobuf:"bytes,1,opt" json:"Content,omitempty"`
	StatusCode            *int32                     `protobuf:"varint,2,req" json:"StatusCode,omitempty"`
	Header                []*URLFetchResponse_Header `protobuf:"group,3,rep" json:"header,omitempty"`
	ContentWasTruncated   *bool                      `protobuf:"varint,6,opt,def=0" json:"ContentWasTruncated,omitempty"`
	ExternalBytesSent     *int64                     `protobuf:"varint,7,opt" json:"ExternalBytesSent,omitempty"`
	ExternalBytesReceived *int64                     `protobuf:"varint,8,opt" json:"ExternalBytesReceived,omitempty"`
	FinalUrl              *string                    `protobuf:"bytes,9,opt" json:"FinalUrl,omitempty"`
	ApiCpuMilliseconds    *int64                     `protobuf:"varint,10,opt,def=0" json:"ApiCpuMilliseconds,omitempty"`
	ApiBytesSent          *int64                     `protobuf:"varint,11,opt,def=0" json:"ApiBytesSent,omitempty"`
	ApiBytesReceived      *int64                     `protobuf:"varint,12,opt,def=0" json:"ApiBytesReceived,omitempty"`
	XXX_unrecognized      []byte                     `json:",omitempty"`
}

func (this *URLFetchResponse) Reset()         { *this = URLFetchResponse{} }
func (this *URLFetchResponse) String() string { return proto.CompactTextString(this) }

const Default_URLFetchResponse_ContentWasTruncated bool = false
const Default_URLFetchResponse_ApiCpuMilliseconds int64 = 0
const Default_URLFetchResponse_ApiBytesSent int64 = 0
const Default_URLFetchResponse_ApiBytesReceived int64 = 0

type URLFetchResponse_Header struct {
	Key              *string `protobuf:"bytes,4,req" json:"Key,omitempty"`
	Value            *string `protobuf:"bytes,5,req" json:"Value,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *URLFetchResponse_Header) Reset()         { *this = URLFetchResponse_Header{} }
func (this *URLFetchResponse_Header) String() string { return proto.CompactTextString(this) }

func init() {
	proto.RegisterEnum("appengine.URLFetchServiceError_ErrorCode", URLFetchServiceError_ErrorCode_name, URLFetchServiceError_ErrorCode_value)
	proto.RegisterEnum("appengine.URLFetchRequest_RequestMethod", URLFetchRequest_RequestMethod_name, URLFetchRequest_RequestMethod_value)
}
