// Code generated by protoc-gen-go from "datastore.proto"
// DO NOT EDIT!

package datastore

import proto "goprotobuf.googlecode.com/hg/proto"
import "math"

// Reference proto, math & os imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf
var _ error

type Property_Meaning int32

const (
	Property_BLOB             Property_Meaning = 14
	Property_TEXT             Property_Meaning = 15
	Property_BYTESTRING       Property_Meaning = 16
	Property_ATOM_CATEGORY    Property_Meaning = 1
	Property_ATOM_LINK        Property_Meaning = 2
	Property_ATOM_TITLE       Property_Meaning = 3
	Property_ATOM_CONTENT     Property_Meaning = 4
	Property_ATOM_SUMMARY     Property_Meaning = 5
	Property_ATOM_AUTHOR      Property_Meaning = 6
	Property_GD_WHEN          Property_Meaning = 7
	Property_GD_EMAIL         Property_Meaning = 8
	Property_GEORSS_POINT     Property_Meaning = 9
	Property_GD_IM            Property_Meaning = 10
	Property_GD_PHONENUMBER   Property_Meaning = 11
	Property_GD_POSTALADDRESS Property_Meaning = 12
	Property_GD_RATING        Property_Meaning = 13
	Property_BLOBKEY          Property_Meaning = 17
)

var Property_Meaning_name = map[int32]string{
	14: "BLOB",
	15: "TEXT",
	16: "BYTESTRING",
	1:  "ATOM_CATEGORY",
	2:  "ATOM_LINK",
	3:  "ATOM_TITLE",
	4:  "ATOM_CONTENT",
	5:  "ATOM_SUMMARY",
	6:  "ATOM_AUTHOR",
	7:  "GD_WHEN",
	8:  "GD_EMAIL",
	9:  "GEORSS_POINT",
	10: "GD_IM",
	11: "GD_PHONENUMBER",
	12: "GD_POSTALADDRESS",
	13: "GD_RATING",
	17: "BLOBKEY",
}
var Property_Meaning_value = map[string]int32{
	"BLOB":             14,
	"TEXT":             15,
	"BYTESTRING":       16,
	"ATOM_CATEGORY":    1,
	"ATOM_LINK":        2,
	"ATOM_TITLE":       3,
	"ATOM_CONTENT":     4,
	"ATOM_SUMMARY":     5,
	"ATOM_AUTHOR":      6,
	"GD_WHEN":          7,
	"GD_EMAIL":         8,
	"GEORSS_POINT":     9,
	"GD_IM":            10,
	"GD_PHONENUMBER":   11,
	"GD_POSTALADDRESS": 12,
	"GD_RATING":        13,
	"BLOBKEY":          17,
}

func NewProperty_Meaning(x Property_Meaning) *Property_Meaning {
	e := Property_Meaning(x)
	return &e
}
func (x Property_Meaning) String() string {
	return proto.EnumName(Property_Meaning_name, int32(x))
}

type EntityProto_Kind int32

const (
	EntityProto_GD_CONTACT EntityProto_Kind = 1
	EntityProto_GD_EVENT   EntityProto_Kind = 2
	EntityProto_GD_MESSAGE EntityProto_Kind = 3
)

var EntityProto_Kind_name = map[int32]string{
	1: "GD_CONTACT",
	2: "GD_EVENT",
	3: "GD_MESSAGE",
}
var EntityProto_Kind_value = map[string]int32{
	"GD_CONTACT": 1,
	"GD_EVENT":   2,
	"GD_MESSAGE": 3,
}

func NewEntityProto_Kind(x EntityProto_Kind) *EntityProto_Kind {
	e := EntityProto_Kind(x)
	return &e
}
func (x EntityProto_Kind) String() string {
	return proto.EnumName(EntityProto_Kind_name, int32(x))
}

type Index_Property_Direction int32

const (
	Index_Property_ASCENDING  Index_Property_Direction = 1
	Index_Property_DESCENDING Index_Property_Direction = 2
)

var Index_Property_Direction_name = map[int32]string{
	1: "ASCENDING",
	2: "DESCENDING",
}
var Index_Property_Direction_value = map[string]int32{
	"ASCENDING":  1,
	"DESCENDING": 2,
}

func NewIndex_Property_Direction(x Index_Property_Direction) *Index_Property_Direction {
	e := Index_Property_Direction(x)
	return &e
}
func (x Index_Property_Direction) String() string {
	return proto.EnumName(Index_Property_Direction_name, int32(x))
}

type CompositeIndex_State int32

const (
	CompositeIndex_WRITE_ONLY CompositeIndex_State = 1
	CompositeIndex_READ_WRITE CompositeIndex_State = 2
	CompositeIndex_DELETED    CompositeIndex_State = 3
	CompositeIndex_ERROR      CompositeIndex_State = 4
)

var CompositeIndex_State_name = map[int32]string{
	1: "WRITE_ONLY",
	2: "READ_WRITE",
	3: "DELETED",
	4: "ERROR",
}
var CompositeIndex_State_value = map[string]int32{
	"WRITE_ONLY": 1,
	"READ_WRITE": 2,
	"DELETED":    3,
	"ERROR":      4,
}

func NewCompositeIndex_State(x CompositeIndex_State) *CompositeIndex_State {
	e := CompositeIndex_State(x)
	return &e
}
func (x CompositeIndex_State) String() string {
	return proto.EnumName(CompositeIndex_State_name, int32(x))
}

type Query_Hint int32

const (
	Query_ORDER_FIRST    Query_Hint = 1
	Query_ANCESTOR_FIRST Query_Hint = 2
	Query_FILTER_FIRST   Query_Hint = 3
)

var Query_Hint_name = map[int32]string{
	1: "ORDER_FIRST",
	2: "ANCESTOR_FIRST",
	3: "FILTER_FIRST",
}
var Query_Hint_value = map[string]int32{
	"ORDER_FIRST":    1,
	"ANCESTOR_FIRST": 2,
	"FILTER_FIRST":   3,
}

func NewQuery_Hint(x Query_Hint) *Query_Hint {
	e := Query_Hint(x)
	return &e
}
func (x Query_Hint) String() string {
	return proto.EnumName(Query_Hint_name, int32(x))
}

type Query_Filter_Operator int32

const (
	Query_Filter_LESS_THAN             Query_Filter_Operator = 1
	Query_Filter_LESS_THAN_OR_EQUAL    Query_Filter_Operator = 2
	Query_Filter_GREATER_THAN          Query_Filter_Operator = 3
	Query_Filter_GREATER_THAN_OR_EQUAL Query_Filter_Operator = 4
	Query_Filter_EQUAL                 Query_Filter_Operator = 5
	Query_Filter_IN                    Query_Filter_Operator = 6
	Query_Filter_EXISTS                Query_Filter_Operator = 7
)

var Query_Filter_Operator_name = map[int32]string{
	1: "LESS_THAN",
	2: "LESS_THAN_OR_EQUAL",
	3: "GREATER_THAN",
	4: "GREATER_THAN_OR_EQUAL",
	5: "EQUAL",
	6: "IN",
	7: "EXISTS",
}
var Query_Filter_Operator_value = map[string]int32{
	"LESS_THAN":             1,
	"LESS_THAN_OR_EQUAL":    2,
	"GREATER_THAN":          3,
	"GREATER_THAN_OR_EQUAL": 4,
	"EQUAL":                 5,
	"IN":                    6,
	"EXISTS":                7,
}

func NewQuery_Filter_Operator(x Query_Filter_Operator) *Query_Filter_Operator {
	e := Query_Filter_Operator(x)
	return &e
}
func (x Query_Filter_Operator) String() string {
	return proto.EnumName(Query_Filter_Operator_name, int32(x))
}

type Query_Order_Direction int32

const (
	Query_Order_ASCENDING  Query_Order_Direction = 1
	Query_Order_DESCENDING Query_Order_Direction = 2
)

var Query_Order_Direction_name = map[int32]string{
	1: "ASCENDING",
	2: "DESCENDING",
}
var Query_Order_Direction_value = map[string]int32{
	"ASCENDING":  1,
	"DESCENDING": 2,
}

func NewQuery_Order_Direction(x Query_Order_Direction) *Query_Order_Direction {
	e := Query_Order_Direction(x)
	return &e
}
func (x Query_Order_Direction) String() string {
	return proto.EnumName(Query_Order_Direction_name, int32(x))
}

type Error_ErrorCode int32

const (
	Error_BAD_REQUEST                  Error_ErrorCode = 1
	Error_CONCURRENT_TRANSACTION       Error_ErrorCode = 2
	Error_INTERNAL_ERROR               Error_ErrorCode = 3
	Error_NEED_INDEX                   Error_ErrorCode = 4
	Error_TIMEOUT                      Error_ErrorCode = 5
	Error_PERMISSION_DENIED            Error_ErrorCode = 6
	Error_BIGTABLE_ERROR               Error_ErrorCode = 7
	Error_COMMITTED_BUT_STILL_APPLYING Error_ErrorCode = 8
	Error_CAPABILITY_DISABLED          Error_ErrorCode = 9
	Error_TRY_ALTERNATE_BACKEND        Error_ErrorCode = 10
)

var Error_ErrorCode_name = map[int32]string{
	1:  "BAD_REQUEST",
	2:  "CONCURRENT_TRANSACTION",
	3:  "INTERNAL_ERROR",
	4:  "NEED_INDEX",
	5:  "TIMEOUT",
	6:  "PERMISSION_DENIED",
	7:  "BIGTABLE_ERROR",
	8:  "COMMITTED_BUT_STILL_APPLYING",
	9:  "CAPABILITY_DISABLED",
	10: "TRY_ALTERNATE_BACKEND",
}
var Error_ErrorCode_value = map[string]int32{
	"BAD_REQUEST":                  1,
	"CONCURRENT_TRANSACTION":       2,
	"INTERNAL_ERROR":               3,
	"NEED_INDEX":                   4,
	"TIMEOUT":                      5,
	"PERMISSION_DENIED":            6,
	"BIGTABLE_ERROR":               7,
	"COMMITTED_BUT_STILL_APPLYING": 8,
	"CAPABILITY_DISABLED":          9,
	"TRY_ALTERNATE_BACKEND":        10,
}

func NewError_ErrorCode(x Error_ErrorCode) *Error_ErrorCode {
	e := Error_ErrorCode(x)
	return &e
}
func (x Error_ErrorCode) String() string {
	return proto.EnumName(Error_ErrorCode_name, int32(x))
}

type Action struct {
	XXX_unrecognized []byte `json:",omitempty"`
}

func (this *Action) Reset()         { *this = Action{} }
func (this *Action) String() string { return proto.CompactTextString(this) }

type StringProto struct {
	Value            *string `protobuf:"bytes,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *StringProto) Reset()         { *this = StringProto{} }
func (this *StringProto) String() string { return proto.CompactTextString(this) }

type Integer32Proto struct {
	Value            *int32 `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:",omitempty"`
}

func (this *Integer32Proto) Reset()         { *this = Integer32Proto{} }
func (this *Integer32Proto) String() string { return proto.CompactTextString(this) }

type Integer64Proto struct {
	Value            *int64 `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:",omitempty"`
}

func (this *Integer64Proto) Reset()         { *this = Integer64Proto{} }
func (this *Integer64Proto) String() string { return proto.CompactTextString(this) }

type BoolProto struct {
	Value            *bool  `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:",omitempty"`
}

func (this *BoolProto) Reset()         { *this = BoolProto{} }
func (this *BoolProto) String() string { return proto.CompactTextString(this) }

type DoubleProto struct {
	Value            *float64 `protobuf:"fixed64,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte   `json:",omitempty"`
}

func (this *DoubleProto) Reset()         { *this = DoubleProto{} }
func (this *DoubleProto) String() string { return proto.CompactTextString(this) }

type BytesProto struct {
	Value            []byte `protobuf:"bytes,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:",omitempty"`
}

func (this *BytesProto) Reset()         { *this = BytesProto{} }
func (this *BytesProto) String() string { return proto.CompactTextString(this) }

type VoidProto struct {
	XXX_unrecognized []byte `json:",omitempty"`
}

func (this *VoidProto) Reset()         { *this = VoidProto{} }
func (this *VoidProto) String() string { return proto.CompactTextString(this) }

type PropertyValue struct {
	Int64Value       *int64                        `protobuf:"varint,1,opt,name=int64Value" json:"int64Value,omitempty"`
	BooleanValue     *bool                         `protobuf:"varint,2,opt,name=booleanValue" json:"booleanValue,omitempty"`
	StringValue      *string                       `protobuf:"bytes,3,opt,name=stringValue" json:"stringValue,omitempty"`
	DoubleValue      *float64                      `protobuf:"fixed64,4,opt,name=doubleValue" json:"doubleValue,omitempty"`
	Pointvalue       *PropertyValue_PointValue     `protobuf:"group,5,opt,name=PointValue" json:"pointvalue,omitempty"`
	Uservalue        *PropertyValue_UserValue      `protobuf:"group,8,opt,name=UserValue" json:"uservalue,omitempty"`
	Referencevalue   *PropertyValue_ReferenceValue `protobuf:"group,12,opt,name=ReferenceValue" json:"referencevalue,omitempty"`
	XXX_unrecognized []byte                        `json:",omitempty"`
}

func (this *PropertyValue) Reset()         { *this = PropertyValue{} }
func (this *PropertyValue) String() string { return proto.CompactTextString(this) }

type PropertyValue_PointValue struct {
	X                *float64 `protobuf:"fixed64,6,req,name=x" json:"x,omitempty"`
	Y                *float64 `protobuf:"fixed64,7,req,name=y" json:"y,omitempty"`
	XXX_unrecognized []byte   `json:",omitempty"`
}

func (this *PropertyValue_PointValue) Reset()         { *this = PropertyValue_PointValue{} }
func (this *PropertyValue_PointValue) String() string { return proto.CompactTextString(this) }

type PropertyValue_UserValue struct {
	Email             *string `protobuf:"bytes,9,req,name=email" json:"email,omitempty"`
	AuthDomain        *string `protobuf:"bytes,10,req,name=auth_domain" json:"auth_domain,omitempty"`
	Nickname          *string `protobuf:"bytes,11,opt,name=nickname" json:"nickname,omitempty"`
	Gaiaid            *int64  `protobuf:"varint,18,req,name=gaiaid" json:"gaiaid,omitempty"`
	ObfuscatedGaiaid  *string `protobuf:"bytes,19,opt,name=obfuscated_gaiaid" json:"obfuscated_gaiaid,omitempty"`
	FederatedIdentity *string `protobuf:"bytes,21,opt,name=federated_identity" json:"federated_identity,omitempty"`
	FederatedProvider *string `protobuf:"bytes,22,opt,name=federated_provider" json:"federated_provider,omitempty"`
	XXX_unrecognized  []byte  `json:",omitempty"`
}

func (this *PropertyValue_UserValue) Reset()         { *this = PropertyValue_UserValue{} }
func (this *PropertyValue_UserValue) String() string { return proto.CompactTextString(this) }

type PropertyValue_ReferenceValue struct {
	App              *string                                     `protobuf:"bytes,13,req,name=app" json:"app,omitempty"`
	NameSpace        *string                                     `protobuf:"bytes,20,opt,name=name_space" json:"name_space,omitempty"`
	Pathelement      []*PropertyValue_ReferenceValue_PathElement `protobuf:"group,14,rep,name=PathElement" json:"pathelement,omitempty"`
	XXX_unrecognized []byte                                      `json:",omitempty"`
}

func (this *PropertyValue_ReferenceValue) Reset()         { *this = PropertyValue_ReferenceValue{} }
func (this *PropertyValue_ReferenceValue) String() string { return proto.CompactTextString(this) }

type PropertyValue_ReferenceValue_PathElement struct {
	Type             *string `protobuf:"bytes,15,req,name=type" json:"type,omitempty"`
	Id               *int64  `protobuf:"varint,16,opt,name=id" json:"id,omitempty"`
	Name             *string `protobuf:"bytes,17,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *PropertyValue_ReferenceValue_PathElement) Reset() {
	*this = PropertyValue_ReferenceValue_PathElement{}
}
func (this *PropertyValue_ReferenceValue_PathElement) String() string {
	return proto.CompactTextString(this)
}

type Property struct {
	Meaning          *Property_Meaning `protobuf:"varint,1,opt,name=meaning,enum=datastore.Property_Meaning" json:"meaning,omitempty"`
	MeaningUri       *string           `protobuf:"bytes,2,opt,name=meaning_uri" json:"meaning_uri,omitempty"`
	Name             *string           `protobuf:"bytes,3,req,name=name" json:"name,omitempty"`
	Value            *PropertyValue    `protobuf:"bytes,5,req,name=value" json:"value,omitempty"`
	Multiple         *bool             `protobuf:"varint,4,req,name=multiple" json:"multiple,omitempty"`
	XXX_unrecognized []byte            `json:",omitempty"`
}

func (this *Property) Reset()         { *this = Property{} }
func (this *Property) String() string { return proto.CompactTextString(this) }

type Path struct {
	Element          []*Path_Element `protobuf:"group,1,rep" json:"element,omitempty"`
	XXX_unrecognized []byte          `json:",omitempty"`
}

func (this *Path) Reset()         { *this = Path{} }
func (this *Path) String() string { return proto.CompactTextString(this) }

type Path_Element struct {
	Type             *string `protobuf:"bytes,2,req,name=type" json:"type,omitempty"`
	Id               *int64  `protobuf:"varint,3,opt,name=id" json:"id,omitempty"`
	Name             *string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *Path_Element) Reset()         { *this = Path_Element{} }
func (this *Path_Element) String() string { return proto.CompactTextString(this) }

type Reference struct {
	App              *string `protobuf:"bytes,13,req,name=app" json:"app,omitempty"`
	NameSpace        *string `protobuf:"bytes,20,opt,name=name_space" json:"name_space,omitempty"`
	Path             *Path   `protobuf:"bytes,14,req,name=path" json:"path,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *Reference) Reset()         { *this = Reference{} }
func (this *Reference) String() string { return proto.CompactTextString(this) }

type User struct {
	Email             *string `protobuf:"bytes,1,req,name=email" json:"email,omitempty"`
	AuthDomain        *string `protobuf:"bytes,2,req,name=auth_domain" json:"auth_domain,omitempty"`
	Nickname          *string `protobuf:"bytes,3,opt,name=nickname" json:"nickname,omitempty"`
	Gaiaid            *int64  `protobuf:"varint,4,req,name=gaiaid" json:"gaiaid,omitempty"`
	ObfuscatedGaiaid  *string `protobuf:"bytes,5,opt,name=obfuscated_gaiaid" json:"obfuscated_gaiaid,omitempty"`
	FederatedIdentity *string `protobuf:"bytes,6,opt,name=federated_identity" json:"federated_identity,omitempty"`
	FederatedProvider *string `protobuf:"bytes,7,opt,name=federated_provider" json:"federated_provider,omitempty"`
	XXX_unrecognized  []byte  `json:",omitempty"`
}

func (this *User) Reset()         { *this = User{} }
func (this *User) String() string { return proto.CompactTextString(this) }

type EntityProto struct {
	Key              *Reference        `protobuf:"bytes,13,req,name=key" json:"key,omitempty"`
	EntityGroup      *Path             `protobuf:"bytes,16,req,name=entity_group" json:"entity_group,omitempty"`
	Owner            *User             `protobuf:"bytes,17,opt,name=owner" json:"owner,omitempty"`
	Kind             *EntityProto_Kind `protobuf:"varint,4,opt,name=kind,enum=datastore.EntityProto_Kind" json:"kind,omitempty"`
	KindUri          *string           `protobuf:"bytes,5,opt,name=kind_uri" json:"kind_uri,omitempty"`
	Property         []*Property       `protobuf:"bytes,14,rep,name=property" json:"property,omitempty"`
	RawProperty      []*Property       `protobuf:"bytes,15,rep,name=raw_property" json:"raw_property,omitempty"`
	XXX_unrecognized []byte            `json:",omitempty"`
}

func (this *EntityProto) Reset()         { *this = EntityProto{} }
func (this *EntityProto) String() string { return proto.CompactTextString(this) }

type CompositeProperty struct {
	IndexId          *int64   `protobuf:"varint,1,req,name=index_id" json:"index_id,omitempty"`
	Value            []string `protobuf:"bytes,2,rep,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte   `json:",omitempty"`
}

func (this *CompositeProperty) Reset()         { *this = CompositeProperty{} }
func (this *CompositeProperty) String() string { return proto.CompactTextString(this) }

type Index struct {
	EntityType       *string           `protobuf:"bytes,1,req,name=entity_type" json:"entity_type,omitempty"`
	Ancestor         *bool             `protobuf:"varint,5,req,name=ancestor" json:"ancestor,omitempty"`
	Property         []*Index_Property `protobuf:"group,2,rep" json:"property,omitempty"`
	XXX_unrecognized []byte            `json:",omitempty"`
}

func (this *Index) Reset()         { *this = Index{} }
func (this *Index) String() string { return proto.CompactTextString(this) }

type Index_Property struct {
	Name             *string                   `protobuf:"bytes,3,req,name=name" json:"name,omitempty"`
	Direction        *Index_Property_Direction `protobuf:"varint,4,opt,name=direction,enum=datastore.Index_Property_Direction,def=1" json:"direction,omitempty"`
	XXX_unrecognized []byte                    `json:",omitempty"`
}

func (this *Index_Property) Reset()         { *this = Index_Property{} }
func (this *Index_Property) String() string { return proto.CompactTextString(this) }

const Default_Index_Property_Direction Index_Property_Direction = Index_Property_ASCENDING

type CompositeIndex struct {
	AppId            *string               `protobuf:"bytes,1,req,name=app_id" json:"app_id,omitempty"`
	Id               *int64                `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Definition       *Index                `protobuf:"bytes,3,req,name=definition" json:"definition,omitempty"`
	State            *CompositeIndex_State `protobuf:"varint,4,req,name=state,enum=datastore.CompositeIndex_State" json:"state,omitempty"`
	XXX_unrecognized []byte                `json:",omitempty"`
}

func (this *CompositeIndex) Reset()         { *this = CompositeIndex{} }
func (this *CompositeIndex) String() string { return proto.CompactTextString(this) }

type Transaction struct {
	Handle           *uint64 `protobuf:"fixed64,1,req,name=handle" json:"handle,omitempty"`
	App              *string `protobuf:"bytes,2,req,name=app" json:"app,omitempty"`
	MarkChanges      *bool   `protobuf:"varint,3,opt,name=mark_changes,def=0" json:"mark_changes,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *Transaction) Reset()         { *this = Transaction{} }
func (this *Transaction) String() string { return proto.CompactTextString(this) }

const Default_Transaction_MarkChanges bool = false

type Query struct {
	App                *string           `protobuf:"bytes,1,req,name=app" json:"app,omitempty"`
	NameSpace          *string           `protobuf:"bytes,29,opt,name=name_space" json:"name_space,omitempty"`
	Kind               *string           `protobuf:"bytes,3,opt,name=kind" json:"kind,omitempty"`
	Ancestor           *Reference        `protobuf:"bytes,17,opt,name=ancestor" json:"ancestor,omitempty"`
	Filter             []*Query_Filter   `protobuf:"group,4,rep" json:"filter,omitempty"`
	SearchQuery        *string           `protobuf:"bytes,8,opt,name=search_query" json:"search_query,omitempty"`
	Order              []*Query_Order    `protobuf:"group,9,rep" json:"order,omitempty"`
	Hint               *Query_Hint       `protobuf:"varint,18,opt,name=hint,enum=datastore.Query_Hint" json:"hint,omitempty"`
	Count              *int32            `protobuf:"varint,23,opt,name=count" json:"count,omitempty"`
	Offset             *int32            `protobuf:"varint,12,opt,name=offset,def=0" json:"offset,omitempty"`
	Limit              *int32            `protobuf:"varint,16,opt,name=limit" json:"limit,omitempty"`
	CompiledCursor     *CompiledCursor   `protobuf:"bytes,30,opt,name=compiled_cursor" json:"compiled_cursor,omitempty"`
	EndCompiledCursor  *CompiledCursor   `protobuf:"bytes,31,opt,name=end_compiled_cursor" json:"end_compiled_cursor,omitempty"`
	CompositeIndex     []*CompositeIndex `protobuf:"bytes,19,rep,name=composite_index" json:"composite_index,omitempty"`
	RequirePerfectPlan *bool             `protobuf:"varint,20,opt,name=require_perfect_plan,def=0" json:"require_perfect_plan,omitempty"`
	KeysOnly           *bool             `protobuf:"varint,21,opt,name=keys_only,def=0" json:"keys_only,omitempty"`
	Transaction        *Transaction      `protobuf:"bytes,22,opt,name=transaction" json:"transaction,omitempty"`
	Distinct           *bool             `protobuf:"varint,24,opt,name=distinct" json:"distinct,omitempty"`
	Compile            *bool             `protobuf:"varint,25,opt,name=compile,def=0" json:"compile,omitempty"`
	FailoverMs         *int64            `protobuf:"varint,26,opt,name=failover_ms" json:"failover_ms,omitempty"`
	Strong             *bool             `protobuf:"varint,32,opt,name=strong" json:"strong,omitempty"`
	XXX_unrecognized   []byte            `json:",omitempty"`
}

func (this *Query) Reset()         { *this = Query{} }
func (this *Query) String() string { return proto.CompactTextString(this) }

const Default_Query_Offset int32 = 0
const Default_Query_RequirePerfectPlan bool = false
const Default_Query_KeysOnly bool = false
const Default_Query_Compile bool = false

type Query_Filter struct {
	Op               *Query_Filter_Operator `protobuf:"varint,6,req,name=op,enum=datastore.Query_Filter_Operator" json:"op,omitempty"`
	Property         []*Property            `protobuf:"bytes,14,rep,name=property" json:"property,omitempty"`
	XXX_unrecognized []byte                 `json:",omitempty"`
}

func (this *Query_Filter) Reset()         { *this = Query_Filter{} }
func (this *Query_Filter) String() string { return proto.CompactTextString(this) }

type Query_Order struct {
	Property         *string                `protobuf:"bytes,10,req,name=property" json:"property,omitempty"`
	Direction        *Query_Order_Direction `protobuf:"varint,11,opt,name=direction,enum=datastore.Query_Order_Direction,def=1" json:"direction,omitempty"`
	XXX_unrecognized []byte                 `json:",omitempty"`
}

func (this *Query_Order) Reset()         { *this = Query_Order{} }
func (this *Query_Order) String() string { return proto.CompactTextString(this) }

const Default_Query_Order_Direction Query_Order_Direction = Query_Order_ASCENDING

type CompiledQuery struct {
	Primaryscan      *CompiledQuery_PrimaryScan     `protobuf:"group,1,req,name=PrimaryScan" json:"primaryscan,omitempty"`
	Mergejoinscan    []*CompiledQuery_MergeJoinScan `protobuf:"group,7,rep,name=MergeJoinScan" json:"mergejoinscan,omitempty"`
	IndexDef         *Index                         `protobuf:"bytes,21,opt,name=index_def" json:"index_def,omitempty"`
	Offset           *int32                         `protobuf:"varint,10,opt,name=offset,def=0" json:"offset,omitempty"`
	Limit            *int32                         `protobuf:"varint,11,opt,name=limit" json:"limit,omitempty"`
	KeysOnly         *bool                          `protobuf:"varint,12,req,name=keys_only" json:"keys_only,omitempty"`
	Entityfilter     *CompiledQuery_EntityFilter    `protobuf:"group,13,opt,name=EntityFilter" json:"entityfilter,omitempty"`
	XXX_unrecognized []byte                         `json:",omitempty"`
}

func (this *CompiledQuery) Reset()         { *this = CompiledQuery{} }
func (this *CompiledQuery) String() string { return proto.CompactTextString(this) }

const Default_CompiledQuery_Offset int32 = 0

type CompiledQuery_PrimaryScan struct {
	IndexName                  *string  `protobuf:"bytes,2,opt,name=index_name" json:"index_name,omitempty"`
	StartKey                   *string  `protobuf:"bytes,3,opt,name=start_key" json:"start_key,omitempty"`
	StartInclusive             *bool    `protobuf:"varint,4,opt,name=start_inclusive" json:"start_inclusive,omitempty"`
	EndKey                     *string  `protobuf:"bytes,5,opt,name=end_key" json:"end_key,omitempty"`
	EndInclusive               *bool    `protobuf:"varint,6,opt,name=end_inclusive" json:"end_inclusive,omitempty"`
	StartPostfixValue          []string `protobuf:"bytes,22,rep,name=start_postfix_value" json:"start_postfix_value,omitempty"`
	EndPostfixValue            []string `protobuf:"bytes,23,rep,name=end_postfix_value" json:"end_postfix_value,omitempty"`
	EndUnappliedLogTimestampUs *int64   `protobuf:"varint,19,opt,name=end_unapplied_log_timestamp_us" json:"end_unapplied_log_timestamp_us,omitempty"`
	XXX_unrecognized           []byte   `json:",omitempty"`
}

func (this *CompiledQuery_PrimaryScan) Reset()         { *this = CompiledQuery_PrimaryScan{} }
func (this *CompiledQuery_PrimaryScan) String() string { return proto.CompactTextString(this) }

type CompiledQuery_MergeJoinScan struct {
	IndexName        *string  `protobuf:"bytes,8,req,name=index_name" json:"index_name,omitempty"`
	PrefixValue      []string `protobuf:"bytes,9,rep,name=prefix_value" json:"prefix_value,omitempty"`
	ValuePrefix      *bool    `protobuf:"varint,20,opt,name=value_prefix,def=0" json:"value_prefix,omitempty"`
	XXX_unrecognized []byte   `json:",omitempty"`
}

func (this *CompiledQuery_MergeJoinScan) Reset()         { *this = CompiledQuery_MergeJoinScan{} }
func (this *CompiledQuery_MergeJoinScan) String() string { return proto.CompactTextString(this) }

const Default_CompiledQuery_MergeJoinScan_ValuePrefix bool = false

type CompiledQuery_EntityFilter struct {
	Distinct         *bool      `protobuf:"varint,14,opt,name=distinct,def=0" json:"distinct,omitempty"`
	Kind             *string    `protobuf:"bytes,17,opt,name=kind" json:"kind,omitempty"`
	Ancestor         *Reference `protobuf:"bytes,18,opt,name=ancestor" json:"ancestor,omitempty"`
	XXX_unrecognized []byte     `json:",omitempty"`
}

func (this *CompiledQuery_EntityFilter) Reset()         { *this = CompiledQuery_EntityFilter{} }
func (this *CompiledQuery_EntityFilter) String() string { return proto.CompactTextString(this) }

const Default_CompiledQuery_EntityFilter_Distinct bool = false

type CompiledCursor struct {
	MultiqueryIndex  *int32                     `protobuf:"varint,1,opt,name=multiquery_index" json:"multiquery_index,omitempty"`
	Position         []*CompiledCursor_Position `protobuf:"group,2,rep" json:"position,omitempty"`
	XXX_unrecognized []byte                     `json:",omitempty"`
}

func (this *CompiledCursor) Reset()         { *this = CompiledCursor{} }
func (this *CompiledCursor) String() string { return proto.CompactTextString(this) }

type CompiledCursor_Position struct {
	StartKey         *string                               `protobuf:"bytes,27,opt,name=start_key" json:"start_key,omitempty"`
	Indexvalue       []*CompiledCursor_Position_IndexValue `protobuf:"group,29,rep,name=IndexValue" json:"indexvalue,omitempty"`
	Key              *Reference                            `protobuf:"bytes,32,opt,name=key" json:"key,omitempty"`
	StartInclusive   *bool                                 `protobuf:"varint,28,opt,name=start_inclusive,def=1" json:"start_inclusive,omitempty"`
	XXX_unrecognized []byte                                `json:",omitempty"`
}

func (this *CompiledCursor_Position) Reset()         { *this = CompiledCursor_Position{} }
func (this *CompiledCursor_Position) String() string { return proto.CompactTextString(this) }

const Default_CompiledCursor_Position_StartInclusive bool = true

type CompiledCursor_Position_IndexValue struct {
	Property         *string        `protobuf:"bytes,30,opt,name=property" json:"property,omitempty"`
	Value            *PropertyValue `protobuf:"bytes,31,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte         `json:",omitempty"`
}

func (this *CompiledCursor_Position_IndexValue) Reset()         { *this = CompiledCursor_Position_IndexValue{} }
func (this *CompiledCursor_Position_IndexValue) String() string { return proto.CompactTextString(this) }

type RunCompiledQueryRequest struct {
	App              *string        `protobuf:"bytes,5,req,name=app" json:"app,omitempty"`
	NameSpace        *string        `protobuf:"bytes,6,opt,name=name_space" json:"name_space,omitempty"`
	CompiledQuery    *CompiledQuery `protobuf:"bytes,1,req,name=compiled_query" json:"compiled_query,omitempty"`
	OriginalQuery    *Query         `protobuf:"bytes,2,opt,name=original_query" json:"original_query,omitempty"`
	Count            *int32         `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
	FailoverMs       *int64         `protobuf:"varint,4,opt,name=failover_ms" json:"failover_ms,omitempty"`
	XXX_unrecognized []byte         `json:",omitempty"`
}

func (this *RunCompiledQueryRequest) Reset()         { *this = RunCompiledQueryRequest{} }
func (this *RunCompiledQueryRequest) String() string { return proto.CompactTextString(this) }

type Cursor struct {
	Cursor           *uint64 `protobuf:"fixed64,1,req,name=cursor" json:"cursor,omitempty"`
	App              *string `protobuf:"bytes,2,opt,name=app" json:"app,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *Cursor) Reset()         { *this = Cursor{} }
func (this *Cursor) String() string { return proto.CompactTextString(this) }

type Error struct {
	XXX_unrecognized []byte `json:",omitempty"`
}

func (this *Error) Reset()        { *this = Error{} }
func (this *Error) Error() string { return proto.CompactTextString(this) }

type Cost struct {
	IndexWrites      *int32           `protobuf:"varint,1,opt,name=index_writes" json:"index_writes,omitempty"`
	IndexWriteBytes  *int32           `protobuf:"varint,2,opt,name=index_write_bytes" json:"index_write_bytes,omitempty"`
	EntityWrites     *int32           `protobuf:"varint,3,opt,name=entity_writes" json:"entity_writes,omitempty"`
	EntityWriteBytes *int32           `protobuf:"varint,4,opt,name=entity_write_bytes" json:"entity_write_bytes,omitempty"`
	Commitcost       *Cost_CommitCost `protobuf:"group,5,opt,name=CommitCost" json:"commitcost,omitempty"`
	XXX_unrecognized []byte           `json:",omitempty"`
}

func (this *Cost) Reset()         { *this = Cost{} }
func (this *Cost) String() string { return proto.CompactTextString(this) }

type Cost_CommitCost struct {
	RequestedEntityPuts    *int32 `protobuf:"varint,6,opt,name=requested_entity_puts" json:"requested_entity_puts,omitempty"`
	RequestedEntityDeletes *int32 `protobuf:"varint,7,opt,name=requested_entity_deletes" json:"requested_entity_deletes,omitempty"`
	XXX_unrecognized       []byte `json:",omitempty"`
}

func (this *Cost_CommitCost) Reset()         { *this = Cost_CommitCost{} }
func (this *Cost_CommitCost) String() string { return proto.CompactTextString(this) }

type GetRequest struct {
	Key              []*Reference `protobuf:"bytes,1,rep,name=key" json:"key,omitempty"`
	Transaction      *Transaction `protobuf:"bytes,2,opt,name=transaction" json:"transaction,omitempty"`
	FailoverMs       *int64       `protobuf:"varint,3,opt,name=failover_ms" json:"failover_ms,omitempty"`
	Strong           *bool        `protobuf:"varint,4,opt,name=strong" json:"strong,omitempty"`
	XXX_unrecognized []byte       `json:",omitempty"`
}

func (this *GetRequest) Reset()         { *this = GetRequest{} }
func (this *GetRequest) String() string { return proto.CompactTextString(this) }

type GetResponse struct {
	Entity           []*GetResponse_Entity `protobuf:"group,1,rep" json:"entity,omitempty"`
	XXX_unrecognized []byte                `json:",omitempty"`
}

func (this *GetResponse) Reset()         { *this = GetResponse{} }
func (this *GetResponse) String() string { return proto.CompactTextString(this) }

type GetResponse_Entity struct {
	Entity           *EntityProto `protobuf:"bytes,2,opt,name=entity" json:"entity,omitempty"`
	XXX_unrecognized []byte       `json:",omitempty"`
}

func (this *GetResponse_Entity) Reset()         { *this = GetResponse_Entity{} }
func (this *GetResponse_Entity) String() string { return proto.CompactTextString(this) }

type PutRequest struct {
	Entity           []*EntityProto    `protobuf:"bytes,1,rep,name=entity" json:"entity,omitempty"`
	Transaction      *Transaction      `protobuf:"bytes,2,opt,name=transaction" json:"transaction,omitempty"`
	CompositeIndex   []*CompositeIndex `protobuf:"bytes,3,rep,name=composite_index" json:"composite_index,omitempty"`
	Trusted          *bool             `protobuf:"varint,4,opt,name=trusted,def=0" json:"trusted,omitempty"`
	Force            *bool             `protobuf:"varint,7,opt,name=force,def=0" json:"force,omitempty"`
	MarkChanges      *bool             `protobuf:"varint,8,opt,name=mark_changes,def=0" json:"mark_changes,omitempty"`
	XXX_unrecognized []byte            `json:",omitempty"`
}

func (this *PutRequest) Reset()         { *this = PutRequest{} }
func (this *PutRequest) String() string { return proto.CompactTextString(this) }

const Default_PutRequest_Trusted bool = false
const Default_PutRequest_Force bool = false
const Default_PutRequest_MarkChanges bool = false

type PutResponse struct {
	Key              []*Reference `protobuf:"bytes,1,rep,name=key" json:"key,omitempty"`
	Cost             *Cost        `protobuf:"bytes,2,opt,name=cost" json:"cost,omitempty"`
	XXX_unrecognized []byte       `json:",omitempty"`
}

func (this *PutResponse) Reset()         { *this = PutResponse{} }
func (this *PutResponse) String() string { return proto.CompactTextString(this) }

type TouchRequest struct {
	Key              []*Reference      `protobuf:"bytes,1,rep,name=key" json:"key,omitempty"`
	CompositeIndex   []*CompositeIndex `protobuf:"bytes,2,rep,name=composite_index" json:"composite_index,omitempty"`
	Force            *bool             `protobuf:"varint,3,opt,name=force,def=0" json:"force,omitempty"`
	XXX_unrecognized []byte            `json:",omitempty"`
}

func (this *TouchRequest) Reset()         { *this = TouchRequest{} }
func (this *TouchRequest) String() string { return proto.CompactTextString(this) }

const Default_TouchRequest_Force bool = false

type TouchResponse struct {
	Cost             *Cost  `protobuf:"bytes,1,opt,name=cost" json:"cost,omitempty"`
	XXX_unrecognized []byte `json:",omitempty"`
}

func (this *TouchResponse) Reset()         { *this = TouchResponse{} }
func (this *TouchResponse) String() string { return proto.CompactTextString(this) }

type DeleteRequest struct {
	Key              []*Reference `protobuf:"bytes,6,rep,name=key" json:"key,omitempty"`
	Transaction      *Transaction `protobuf:"bytes,5,opt,name=transaction" json:"transaction,omitempty"`
	Trusted          *bool        `protobuf:"varint,4,opt,name=trusted,def=0" json:"trusted,omitempty"`
	Force            *bool        `protobuf:"varint,7,opt,name=force,def=0" json:"force,omitempty"`
	MarkChanges      *bool        `protobuf:"varint,8,opt,name=mark_changes,def=0" json:"mark_changes,omitempty"`
	XXX_unrecognized []byte       `json:",omitempty"`
}

func (this *DeleteRequest) Reset()         { *this = DeleteRequest{} }
func (this *DeleteRequest) String() string { return proto.CompactTextString(this) }

const Default_DeleteRequest_Trusted bool = false
const Default_DeleteRequest_Force bool = false
const Default_DeleteRequest_MarkChanges bool = false

type DeleteResponse struct {
	Cost             *Cost  `protobuf:"bytes,1,opt,name=cost" json:"cost,omitempty"`
	XXX_unrecognized []byte `json:",omitempty"`
}

func (this *DeleteResponse) Reset()         { *this = DeleteResponse{} }
func (this *DeleteResponse) String() string { return proto.CompactTextString(this) }

type NextRequest struct {
	Cursor           *Cursor `protobuf:"bytes,1,req,name=cursor" json:"cursor,omitempty"`
	Count            *int32  `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	Offset           *int32  `protobuf:"varint,4,opt,name=offset,def=0" json:"offset,omitempty"`
	Compile          *bool   `protobuf:"varint,3,opt,name=compile,def=0" json:"compile,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *NextRequest) Reset()         { *this = NextRequest{} }
func (this *NextRequest) String() string { return proto.CompactTextString(this) }

const Default_NextRequest_Offset int32 = 0
const Default_NextRequest_Compile bool = false

type QueryResult struct {
	Cursor           *Cursor         `protobuf:"bytes,1,opt,name=cursor" json:"cursor,omitempty"`
	Result           []*EntityProto  `protobuf:"bytes,2,rep,name=result" json:"result,omitempty"`
	SkippedResults   *int32          `protobuf:"varint,7,opt,name=skipped_results" json:"skipped_results,omitempty"`
	MoreResults      *bool           `protobuf:"varint,3,req,name=more_results" json:"more_results,omitempty"`
	KeysOnly         *bool           `protobuf:"varint,4,opt,name=keys_only" json:"keys_only,omitempty"`
	CompiledQuery    *CompiledQuery  `protobuf:"bytes,5,opt,name=compiled_query" json:"compiled_query,omitempty"`
	CompiledCursor   *CompiledCursor `protobuf:"bytes,6,opt,name=compiled_cursor" json:"compiled_cursor,omitempty"`
	XXX_unrecognized []byte          `json:",omitempty"`
}

func (this *QueryResult) Reset()         { *this = QueryResult{} }
func (this *QueryResult) String() string { return proto.CompactTextString(this) }

type AllocateIdsRequest struct {
	ModelKey         *Reference `protobuf:"bytes,1,req,name=model_key" json:"model_key,omitempty"`
	Size             *int64     `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	Max              *int64     `protobuf:"varint,3,opt,name=max" json:"max,omitempty"`
	XXX_unrecognized []byte     `json:",omitempty"`
}

func (this *AllocateIdsRequest) Reset()         { *this = AllocateIdsRequest{} }
func (this *AllocateIdsRequest) String() string { return proto.CompactTextString(this) }

type AllocateIdsResponse struct {
	Start            *int64 `protobuf:"varint,1,req,name=start" json:"start,omitempty"`
	End              *int64 `protobuf:"varint,2,req,name=end" json:"end,omitempty"`
	XXX_unrecognized []byte `json:",omitempty"`
}

func (this *AllocateIdsResponse) Reset()         { *this = AllocateIdsResponse{} }
func (this *AllocateIdsResponse) String() string { return proto.CompactTextString(this) }

type CompositeIndices struct {
	Index            []*CompositeIndex `protobuf:"bytes,1,rep,name=index" json:"index,omitempty"`
	XXX_unrecognized []byte            `json:",omitempty"`
}

func (this *CompositeIndices) Reset()         { *this = CompositeIndices{} }
func (this *CompositeIndices) String() string { return proto.CompactTextString(this) }

type AddActionsRequest struct {
	Transaction      *Transaction `protobuf:"bytes,1,req,name=transaction" json:"transaction,omitempty"`
	Action           []*Action    `protobuf:"bytes,2,rep,name=action" json:"action,omitempty"`
	XXX_unrecognized []byte       `json:",omitempty"`
}

func (this *AddActionsRequest) Reset()         { *this = AddActionsRequest{} }
func (this *AddActionsRequest) String() string { return proto.CompactTextString(this) }

type AddActionsResponse struct {
	XXX_unrecognized []byte `json:",omitempty"`
}

func (this *AddActionsResponse) Reset()         { *this = AddActionsResponse{} }
func (this *AddActionsResponse) String() string { return proto.CompactTextString(this) }

type BeginTransactionRequest struct {
	App              *string `protobuf:"bytes,1,req,name=app" json:"app,omitempty"`
	AllowMultipleEg  *bool   `protobuf:"varint,2,opt,name=allow_multiple_eg,def=0" json:"allow_multiple_eg,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *BeginTransactionRequest) Reset()         { *this = BeginTransactionRequest{} }
func (this *BeginTransactionRequest) String() string { return proto.CompactTextString(this) }

const Default_BeginTransactionRequest_AllowMultipleEg bool = false

type CommitResponse struct {
	Cost             *Cost  `protobuf:"bytes,1,opt,name=cost" json:"cost,omitempty"`
	XXX_unrecognized []byte `json:",omitempty"`
}

func (this *CommitResponse) Reset()         { *this = CommitResponse{} }
func (this *CommitResponse) String() string { return proto.CompactTextString(this) }

func init() {
	proto.RegisterEnum("datastore.Property_Meaning", Property_Meaning_name, Property_Meaning_value)
	proto.RegisterEnum("datastore.EntityProto_Kind", EntityProto_Kind_name, EntityProto_Kind_value)
	proto.RegisterEnum("datastore.Index_Property_Direction", Index_Property_Direction_name, Index_Property_Direction_value)
	proto.RegisterEnum("datastore.CompositeIndex_State", CompositeIndex_State_name, CompositeIndex_State_value)
	proto.RegisterEnum("datastore.Query_Hint", Query_Hint_name, Query_Hint_value)
	proto.RegisterEnum("datastore.Query_Filter_Operator", Query_Filter_Operator_name, Query_Filter_Operator_value)
	proto.RegisterEnum("datastore.Query_Order_Direction", Query_Order_Direction_name, Query_Order_Direction_value)
	proto.RegisterEnum("datastore.Error_ErrorCode", Error_ErrorCode_name, Error_ErrorCode_value)
}
