application: helloworld
version: 1
runtime: go
api_version: 2

handlers:
- url: /(robots\.txt|favicon\.ico)
  static_files: static/\1
  upload: static/.*

- url: /static
  static_dir: static

- url: .*
  script: _go_app
