// Code generated by protoc-gen-go from "log_service.proto"
// DO NOT EDIT!

package appengine

import proto "goprotobuf.googlecode.com/hg/proto"
import "math"
import "os"

// Reference proto, math & os imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf
var _ os.Error

type LogServiceError_ErrorCode int32

const (
	LogServiceError_OK              LogServiceError_ErrorCode = 0
	LogServiceError_INVALID_REQUEST LogServiceError_ErrorCode = 1
	LogServiceError_STORAGE_ERROR   LogServiceError_ErrorCode = 2
)

var LogServiceError_ErrorCode_name = map[int32]string{
	0: "OK",
	1: "INVALID_REQUEST",
	2: "STORAGE_ERROR",
}
var LogServiceError_ErrorCode_value = map[string]int32{
	"OK":              0,
	"INVALID_REQUEST": 1,
	"STORAGE_ERROR":   2,
}

func NewLogServiceError_ErrorCode(x LogServiceError_ErrorCode) *LogServiceError_ErrorCode {
	e := LogServiceError_ErrorCode(x)
	return &e
}
func (x LogServiceError_ErrorCode) String() string {
	return proto.EnumName(LogServiceError_ErrorCode_name, int32(x))
}

type LogServiceError struct {
	XXX_unrecognized []byte `json:",omitempty"`
}

func (this *LogServiceError) Reset()         { *this = LogServiceError{} }
func (this *LogServiceError) String() string { return proto.CompactTextString(this) }

type UserAppLogLine struct {
	TimestampUsec    *int64  `protobuf:"varint,1,req,name=timestamp_usec" json:"timestamp_usec,omitempty"`
	Level            *int64  `protobuf:"varint,2,req,name=level" json:"level,omitempty"`
	Message          *string `protobuf:"bytes,3,req,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *UserAppLogLine) Reset()         { *this = UserAppLogLine{} }
func (this *UserAppLogLine) String() string { return proto.CompactTextString(this) }

type UserAppLogGroup struct {
	LogLine          []*UserAppLogLine `protobuf:"bytes,2,rep,name=log_line" json:"log_line,omitempty"`
	XXX_unrecognized []byte            `json:",omitempty"`
}

func (this *UserAppLogGroup) Reset()         { *this = UserAppLogGroup{} }
func (this *UserAppLogGroup) String() string { return proto.CompactTextString(this) }

type FlushRequest struct {
	Logs             []byte `protobuf:"bytes,1,opt,name=logs" json:"logs,omitempty"`
	XXX_unrecognized []byte `json:",omitempty"`
}

func (this *FlushRequest) Reset()         { *this = FlushRequest{} }
func (this *FlushRequest) String() string { return proto.CompactTextString(this) }

type SetStatusRequest struct {
	Status           *string `protobuf:"bytes,1,req,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *SetStatusRequest) Reset()         { *this = SetStatusRequest{} }
func (this *SetStatusRequest) String() string { return proto.CompactTextString(this) }

type LogOffset struct {
	RequestId        *string `protobuf:"bytes,1,opt,name=request_id" json:"request_id,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *LogOffset) Reset()         { *this = LogOffset{} }
func (this *LogOffset) String() string { return proto.CompactTextString(this) }

type LogLine struct {
	Time             *int64  `protobuf:"varint,1,req,name=time" json:"time,omitempty"`
	Level            *int32  `protobuf:"varint,2,req,name=level" json:"level,omitempty"`
	LogMessage       *string `protobuf:"bytes,3,req,name=log_message" json:"log_message,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *LogLine) Reset()         { *this = LogLine{} }
func (this *LogLine) String() string { return proto.CompactTextString(this) }

type RequestLog struct {
	AppId                   *string    `protobuf:"bytes,1,req,name=app_id" json:"app_id,omitempty"`
	VersionId               *string    `protobuf:"bytes,2,req,name=version_id" json:"version_id,omitempty"`
	RequestId               *string    `protobuf:"bytes,3,req,name=request_id" json:"request_id,omitempty"`
	Ip                      *string    `protobuf:"bytes,4,req,name=ip" json:"ip,omitempty"`
	Nickname                *string    `protobuf:"bytes,5,opt,name=nickname" json:"nickname,omitempty"`
	StartTime               *int64     `protobuf:"varint,6,req,name=start_time" json:"start_time,omitempty"`
	EndTime                 *int64     `protobuf:"varint,7,req,name=end_time" json:"end_time,omitempty"`
	Latency                 *int64     `protobuf:"varint,8,req,name=latency" json:"latency,omitempty"`
	Mcycles                 *int64     `protobuf:"varint,9,req,name=mcycles" json:"mcycles,omitempty"`
	Method                  *string    `protobuf:"bytes,10,req,name=method" json:"method,omitempty"`
	Resource                *string    `protobuf:"bytes,11,req,name=resource" json:"resource,omitempty"`
	HttpVersion             *string    `protobuf:"bytes,12,req,name=http_version" json:"http_version,omitempty"`
	Status                  *int32     `protobuf:"varint,13,req,name=status" json:"status,omitempty"`
	ResponseSize            *int64     `protobuf:"varint,14,req,name=response_size" json:"response_size,omitempty"`
	Referrer                *string    `protobuf:"bytes,15,opt,name=referrer" json:"referrer,omitempty"`
	UserAgent               *string    `protobuf:"bytes,16,opt,name=user_agent" json:"user_agent,omitempty"`
	UrlMapEntry             *string    `protobuf:"bytes,17,req,name=url_map_entry" json:"url_map_entry,omitempty"`
	Combined                *string    `protobuf:"bytes,18,req,name=combined" json:"combined,omitempty"`
	ApiMcycles              *int64     `protobuf:"varint,19,opt,name=api_mcycles" json:"api_mcycles,omitempty"`
	Host                    *string    `protobuf:"bytes,20,opt,name=host" json:"host,omitempty"`
	Cost                    *float64   `protobuf:"fixed64,21,opt,name=cost" json:"cost,omitempty"`
	TaskQueueName           *string    `protobuf:"bytes,22,opt,name=task_queue_name" json:"task_queue_name,omitempty"`
	TaskName                *string    `protobuf:"bytes,23,opt,name=task_name" json:"task_name,omitempty"`
	WasLoadingRequest       *bool      `protobuf:"varint,24,opt,name=was_loading_request" json:"was_loading_request,omitempty"`
	PendingTime             *int64     `protobuf:"varint,25,opt,name=pending_time" json:"pending_time,omitempty"`
	ReplicaIndex            *int32     `protobuf:"varint,26,opt,name=replica_index,def=-1" json:"replica_index,omitempty"`
	Finished                *bool      `protobuf:"varint,27,opt,name=finished,def=1" json:"finished,omitempty"`
	CloneKey                []byte     `protobuf:"bytes,28,opt,name=clone_key" json:"clone_key,omitempty"`
	Line                    []*LogLine `protobuf:"bytes,29,rep,name=line" json:"line,omitempty"`
	ExitReason              *int32     `protobuf:"varint,30,opt,name=exit_reason" json:"exit_reason,omitempty"`
	WasThrottledForTime     *bool      `protobuf:"varint,31,opt,name=was_throttled_for_time" json:"was_throttled_for_time,omitempty"`
	WasThrottledForRequests *bool      `protobuf:"varint,32,opt,name=was_throttled_for_requests" json:"was_throttled_for_requests,omitempty"`
	ThrottledTime           *int64     `protobuf:"varint,33,opt,name=throttled_time" json:"throttled_time,omitempty"`
	ServerName              []byte     `protobuf:"bytes,34,opt,name=server_name" json:"server_name,omitempty"`
	XXX_unrecognized        []byte     `json:",omitempty"`
}

func (this *RequestLog) Reset()         { *this = RequestLog{} }
func (this *RequestLog) String() string { return proto.CompactTextString(this) }

const Default_RequestLog_ReplicaIndex int32 = -1
const Default_RequestLog_Finished bool = true

type LogReadRequest struct {
	AppId             *string    `protobuf:"bytes,1,req,name=app_id" json:"app_id,omitempty"`
	VersionId         []string   `protobuf:"bytes,2,rep,name=version_id" json:"version_id,omitempty"`
	StartTime         *int64     `protobuf:"varint,3,opt,name=start_time" json:"start_time,omitempty"`
	EndTime           *int64     `protobuf:"varint,4,opt,name=end_time" json:"end_time,omitempty"`
	Offset            *LogOffset `protobuf:"bytes,5,opt,name=offset" json:"offset,omitempty"`
	RequestId         []string   `protobuf:"bytes,6,rep,name=request_id" json:"request_id,omitempty"`
	MinimumLogLevel   *int32     `protobuf:"varint,7,opt,name=minimum_log_level" json:"minimum_log_level,omitempty"`
	IncludeIncomplete *bool      `protobuf:"varint,8,opt,name=include_incomplete" json:"include_incomplete,omitempty"`
	Count             *int64     `protobuf:"varint,9,opt,name=count" json:"count,omitempty"`
	IncludeAppLogs    *bool      `protobuf:"varint,10,opt,name=include_app_logs" json:"include_app_logs,omitempty"`
	IncludeHost       *bool      `protobuf:"varint,11,opt,name=include_host" json:"include_host,omitempty"`
	IncludeAll        *bool      `protobuf:"varint,12,opt,name=include_all" json:"include_all,omitempty"`
	CacheIterator     *bool      `protobuf:"varint,13,opt,name=cache_iterator" json:"cache_iterator,omitempty"`
	XXX_unrecognized  []byte     `json:",omitempty"`
}

func (this *LogReadRequest) Reset()         { *this = LogReadRequest{} }
func (this *LogReadRequest) String() string { return proto.CompactTextString(this) }

type LogReadResponse struct {
	Log              []*RequestLog `protobuf:"bytes,1,rep,name=log" json:"log,omitempty"`
	Offset           *LogOffset    `protobuf:"bytes,2,opt,name=offset" json:"offset,omitempty"`
	XXX_unrecognized []byte        `json:",omitempty"`
}

func (this *LogReadResponse) Reset()         { *this = LogReadResponse{} }
func (this *LogReadResponse) String() string { return proto.CompactTextString(this) }

func init() {
	proto.RegisterEnum("appengine.LogServiceError_ErrorCode", LogServiceError_ErrorCode_name, LogServiceError_ErrorCode_value)
}
