include ${GOROOT}/src/Make.inc

TARG=gorilla.googlecode.com/hg/gorilla/mux

GOFILES=\
	defaultrouter.go\
	doc.go\
	matchers.go\
	mux.go\
	route.go\

DEPS=\
	gorilla.googlecode.com/hg/gorilla/context\

include ${GOROOT}/src/Make.pkg
